project:
  type: website

website:
  search: false
  title: "Emily McLeod"
  navbar:
    left:
      - text: "Publications"
        href: publications.qmd

format:
  html:
    theme: custom-theme.scss
    css: styles.css

editor: visual
 